services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/yourusername/your-repo-name
    branch: main
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: MySecureVault
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: laravel-db
          property: connectionString
      - key: MONGO_DB_CONNECTION
        value: mongodb
      - key: MONGO_DB_URI
        sync: false
      - key: MONGO_DB_DATABASE
        value: your_mongo_database
      - key: MONGO_DB_AUTHENTICATION_DATABASE
        value: admin
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: MySecureVault
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: NODE_ENV
        value: production
      - key: SASS_DEPRECATE_WARNINGS
        value: "0"

databases:
  - name: laravel-db
    databaseName: laravel
    plan: free 