services:
  - type: web
    name: laravel-app
    env: docker
    rootDir: .
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: MySecureVault
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: laravel-app
          property: host
      - key: TRUSTED_PROXIES
        value: "*"
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGO_DB_URI
        sync: false
      - key: MONGO_DB_HOST
        value: cluster0.1pi1ngi.mongodb.net
      - key: MONGO_DB_DATABASE
        value: my_project
      - key: MONGO_DB_USERNAME
        sync: false
      - key: MONGO_DB_PASSWORD
        sync: false
      - key: MONGO_DB_AUTHENTICATION_DATABASE
        value: admin
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: MySecureVault
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 10 