services:
  - type: web
    name: MySecureVault
    env: docker
    plan: free
    dockerfilePath: Dockerfile.render
    healthCheckPath: /index.html
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "27017"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false

databases:
  - name: mongodb
    plan: free
    ipAllowList: [] 